basic.forever(function () {
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 150)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 150)
    basic.pause(1000)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 0)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 0)
    basic.pause(1000)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 150)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 150)
    basic.pause(1000)
})
